export const ADD_CONTACT = "ADD_CONTACT";
export const LOAD_CONTACTS = "LOAD_CONTACTS";
export const DELETE_CONTACT = "DELETE_CONTACT";
export const LOAD_A_CONTACT = "LOAD_A_CONTACT";
export const LOAD_A_CONTACT_ERROR = "LOAD_A_CONTACT_ERROR";
export const UPDATE_A_CONTACT = "UPDATE_A_CONTACT";
export const UPDATE_A_CONTACT_ERROR = "UPDATE_A_CONTACT_ERROR"